(in-package #:cl-tui-kit/tests)

(deftest backend-testing-diff-and-capabilities (:backend)
  (let* ((backend (make-test-backend
                   :size (make-size 6 2)
                   :capabilities (make-backend-capabilities
                                  :color :truecolor
                                  :unicode :full
                                  :mouse :basic
                                  :clipboard t
                                  :alternate-screen nil)))
         (surface (make-surface 6 2)))
    (surface-draw-text surface 0 0 "ok")
    (backend-present backend surface)
    (surface-clear surface)
    (is (surface-equal-p surface (make-surface 6 2)))
    (is (test-backend-last-frame backend))
    (is (not (surface-equal-p surface (test-backend-last-frame backend))))
    (test-backend-emit backend (make-custom-event :refresh))
    (is-equal 1 (length (test-backend-recorded-events backend)))
    (backend-resize backend 20 4)
    (is-equal 20 (size-width (backend-size backend)))
    (is-equal :supported (backend-capability-state backend :clipboard))
    (is (not (backend-capabilities-alternate-screen
              (backend-capabilities backend))))))

(deftest backend-lifecycle-and-capability-states (:backend)
  (let ((backend (make-test-backend
                  :capabilities (make-backend-capabilities
                                 :mouse :unknown
                                 :clipboard nil))))
    (is-equal :closed (backend-state backend))
    (is-equal :unknown (backend-capability-state backend :mouse))
    (is-equal :unsupported (backend-capability-state backend :clipboard))
    (backend-open backend)
    (is-equal :open (backend-state backend))
    (backend-close backend)
    (is-equal :closed (backend-state backend))
    (is (member '(:open) (test-backend-operations backend) :test #'equal))
    (is (member '(:close) (test-backend-operations backend) :test #'equal))))

(deftest backend-capability-state-mutation (:backend)
  (let ((backend (make-test-backend
                  :capabilities (make-backend-capabilities
                                 :clipboard nil))))
    (is-equal :unsupported (backend-capability-state backend :clipboard))
    (backend-set-capability backend :clipboard t)
    (is-equal :supported (backend-capability-state backend :clipboard))
    (backend-set-capability-state backend :mouse :unknown)
    (is-equal :unknown (backend-capability-state backend :mouse))
    (backend-set-capability-state backend :mouse :supported :value :basic)
    (is-equal :supported (backend-capability-state backend :mouse))
    (is (signals-error
         (backend-set-capability-state backend :mouse :degraded)))))

(deftest backend-output-state-and-capability-contracts (:backend)
  (let ((backend (make-backend
                  :size (make-size 3 2)
                  :capabilities (make-backend-capabilities
                                 :alternate-screen nil))))
    (is-equal :unsupported (backend-capability-state backend :clipboard))
    (backend-set-capability backend :clipboard "osc52")
    (backend-set-capability-state backend :clipboard :supported)
    (is-equal "osc52" (backend-capability backend :clipboard))
    (is (backend-supports-p backend :clipboard))
    (backend-set-capability-state backend :clipboard :error)
    (is-equal :error (backend-capability-state backend :clipboard))
    (is (not (backend-supports-p backend :clipboard)))
    (backend-set-capability-state backend :clipboard :supported)
    (backend-set-cursor backend (make-point 2 1))
    (is-equal 2 (point-x (backend-cursor backend)))
    (is-equal 1 (point-y (backend-cursor backend)))
    (backend-set-cursor-visible backend nil)
    (is (not (backend-cursor-visible backend)))
    (backend-set-title backend "title")
    (is-equal "title" (backend-title backend))
    (backend-clear-title backend)
    (is (null (backend-title backend)))
    (backend-enter-alternate backend)
    (is (not (backend-alternate-screen-p backend)))
    (let ((condition nil))
      (handler-case (error "expected backend failure")
        (error (caught) (setf condition caught)))
      (backend-fail backend condition)
      (is-equal :failed (backend-state backend))
      (is (eq condition (backend-last-error backend))))
    (backend-open backend)
    (is-equal :open (backend-state backend))
    (is (null (backend-last-error backend)))
    (backend-close backend)
    (is-equal :closed (backend-state backend)))
  (let ((backend (make-backend)))
    (multiple-value-bind (value status) (backend-read-clipboard backend)
      (is (null value))
      (is-equal :unsupported status))
    (multiple-value-bind (written-p status)
        (backend-write-clipboard backend "text")
      (is (not written-p))
      (is-equal :unsupported status))
    (is (null (backend-capability backend :unknown)))
    (is (signals-error (backend-set-capability backend :color 4)))
    (is (signals-error
         (backend-set-capability-state backend :clipboard :degraded)))))

(deftest backend-capability-copy-and-default-protocol (:backend)
  (let ((states (make-hash-table :test #'eq)))
    (setf (gethash :mouse states) :supported)
    (let ((backend (make-backend
                    :size (make-size 4 3)
                    :capability-states states)))
      (setf (gethash :mouse states) :error)
      (is-equal :supported (backend-capability-state backend :mouse))
      (backend-set-capability backend :color :truecolor)
      (backend-set-capability backend :unicode :full)
      (backend-set-capability backend :mouse :sgr)
      (backend-set-capability backend :alternate-screen t)
      (is-equal :truecolor (backend-capability backend :color))
      (is-equal :full (backend-capability backend :unicode))
      (is-equal :sgr (backend-capability backend :mouse))
      (is (backend-capability backend :alternate-screen))
      (is (null (backend-resized backend (make-size 4 3) (make-size 5 4))))
      (is (null (backend-begin-frame backend)))
      (is (null (backend-present backend (make-surface 5 4))))
      (is (null (backend-flush backend)))
      (is (null (backend-invalidate backend)))))
  (is (signals-error (make-backend :capability-states :invalid))))

(deftest test-backend-last-frame-is-latest (:backend)
  (let ((backend (make-test-backend :size (make-size 4 1)))
        (surface (make-surface 4 1)))
    (surface-draw-text surface 0 0 "first")
    (backend-present backend surface)
    (surface-clear surface)
    (surface-draw-text surface 0 0 "last")
    (backend-present backend surface)
    (is-equal 2 (length (test-backend-frames backend)))
    (is-equal "last" (surface-string (test-backend-last-frame backend)))))

(deftest ansi-backend-and-structured-frame (:ansi)
  (let* ((stream (make-string-output-stream))
         (backend (make-ansi-backend :stream stream :size (make-size 4 1)))
         (surface (make-surface 4 1)))
    (surface-draw-text surface 0 0 "x")
    (backend-present backend surface)
    (backend-flush backend)
    (is (search (string (code-char 27)) (get-output-stream-string stream)))
    (is (ansi-backend-previous-surface backend)))
  (let* ((stream (make-string-output-stream))
         (backend (make-ansi-backend :stream stream :size (make-size 4 1)))
         (surface (make-surface 4 1)))
    (surface-draw-text surface 0 0 "日")
    (backend-present backend surface)
    (let ((output (get-output-stream-string stream)))
      (is (search (format nil "~C[1;1H" (code-char 27)) output))
      (is (not (search (format nil "~C[1;2H" (code-char 27)) output)))))
  (let* ((stream (make-string-output-stream))
         (backend (make-ansi-backend
                   :stream stream
                   :capabilities (make-backend-capabilities :clipboard t))))
    (multiple-value-bind (written-p status)
        (backend-write-clipboard backend "日")
      (is written-p)
      (is-equal :ok status))
    (let ((output (get-output-stream-string stream)))
      (is (search (format nil "~C]52;c;" (code-char 27)) output))
      (is (search "5pel" output)))))

(deftest ansi-clipboard-query-contract (:ansi)
  (let* ((stream (make-string-output-stream))
         (backend (make-ansi-backend
                   :stream stream
                   :capabilities (make-backend-capabilities :clipboard t))))
    (multiple-value-bind (requested-p status)
        (backend-request-clipboard backend :selection "p")
      (is requested-p)
      (is-equal :pending status))
    (let ((output (get-output-stream-string stream)))
      (is (search (format nil "~C]52;p;?~C"
                         (code-char 27) (code-char 7))
                  output)))
    (is (signals-error
         (backend-request-clipboard backend :selection "bad;selection"))))
  (let* ((stream (make-string-output-stream))
         (backend (make-ansi-backend
                   :stream stream
                   :capabilities (make-backend-capabilities :clipboard nil))))
    (multiple-value-bind (requested-p status)
        (ansi-request-clipboard backend)
      (is (not requested-p))
      (is-equal :unsupported status))
    (is-equal "" (get-output-stream-string stream))))

(deftest ansi-output-control-and-color-contracts (:ansi)
  (let ((style (make-style :foreground (rgb-color 1 2 3)
                           :background (indexed-color 4)
                           :bold t :dim t :italic t :underline t
                           :reverse t :strike t)))
    (let ((encoded (ansi-encode-style style)))
      (dolist (fragment '("0;" "1" "2" "3" "4" "7" "9"
                          "38;2;1;2;3" "48;5;4"))
        (is (search fragment encoded)))))
  (let ((style (make-style)))
    (dolist (capability '(:basic :256 :truecolor))
      (let ((encoded (ansi-encode-style style :color-capability capability)))
        (is (search "39" encoded))
        (is (search "49" encoded)))))
  (dolist (capability '(:basic :256 :truecolor))
    (let ((encoded (ansi-encode-style
                    (make-style :foreground (named-color :not-a-palette))
                    :color-capability capability)))
      (is (stringp encoded))))
  (dolist (capability '(:basic :256 :truecolor))
    (let ((encoded (ansi-encode-style
                    (make-style :foreground (make-color :unsupported))
                    :color-capability capability)))
      (is (stringp encoded))))
  (dolist (index '(0 16 232))
    (is (stringp (ansi-encode-style
                  (make-style :foreground (indexed-color index))
                  :color-capability :basic))))
  (is (search "38;5;16"
              (ansi-encode-style
               (make-style :foreground (indexed-color 16))
               :color-capability :truecolor)))
  (let* ((stream (make-string-output-stream))
         (backend (make-ansi-backend
                   :stream stream
                   :size (make-size 4 1)
                   :capabilities
                   (make-backend-capabilities
                    :color :truecolor :unicode :full
                    :clipboard t :alternate-screen t))))
    (backend-set-cursor backend (make-point 2 0))
    (backend-set-cursor-visible backend nil)
    (backend-enter-alternate backend)
    (backend-leave-alternate backend)
    (backend-set-title backend
                       (format nil "a~Cbad~C~C"
                               (code-char 27) #\Newline #\Bell))
    (backend-clear-title backend)
    (multiple-value-bind (written-p status)
        (backend-write-clipboard backend "hello")
      (is written-p)
      (is-equal :ok status))
    (multiple-value-bind (written-p status)
        (backend-write-clipboard backend "a")
      (is written-p)
      (is-equal :ok status))
    (multiple-value-bind (written-p status)
        (backend-write-clipboard backend "¢😀")
      (is written-p)
      (is-equal :ok status))
    (multiple-value-bind (text status)
        (backend-read-clipboard backend)
      (is (null text))
      (is-equal :unsupported status))
    (let ((surface (make-surface 4 1)))
      (surface-draw-text surface 0 0 "x")
      (backend-present backend surface :region (make-rectangle 0 0 1 1))
      (is (null (ansi-backend-previous-surface backend)))
      (backend-present backend surface)
      (is (ansi-backend-previous-surface backend))
      (backend-present backend (make-surface 4 1))
      (backend-resize backend 5 2)
      (is (null (ansi-backend-previous-surface backend))))
    (backend-reset-output backend)
    (backend-flush backend)
    (let ((output (get-output-stream-string stream)))
      (is (search (format nil "~C[1;3H" (code-char 27)) output))
      (is (search (format nil "~C[?25l" (code-char 27)) output))
      (is (search (format nil "~C[?1049h" (code-char 27)) output))
      (is (search (format nil "~C[?1049l" (code-char 27)) output))
      (is (search (format nil "~C]2;abad" (code-char 27)) output))
      (is (search (format nil "~C]2;~C" (code-char 27) (code-char 7))
                  output))
      (is (search (format nil "~C]52;c;aGVsbG8=" (code-char 27))
                  output))
      (is (search (format nil "~C]52;c;YQ==" (code-char 27)) output))
      (is (search (format nil "~C]52;c;wqLwn5iA" (code-char 27)) output))
      (is (search (format nil "~C[0m" (code-char 27)) output))))
  (let* ((stream (make-string-output-stream))
         (backend (make-ansi-backend
                   :stream stream
                   :capabilities (make-backend-capabilities
                                  :alternate-screen nil
                                  :clipboard nil))))
    (multiple-value-bind (written-p status)
        (backend-write-clipboard backend "hello")
      (is (not written-p))
      (is-equal :unsupported status))
    (backend-enter-alternate backend)
    (is-equal "" (get-output-stream-string stream))))

(deftest ansi-terminal-mode-controls (:ansi)
  (let* ((stream (make-string-output-stream))
         (backend (make-ansi-backend :stream stream)))
    (backend-open backend)
    (ansi-enable-mouse-reporting backend :mode :any-motion)
    (ansi-enable-bracketed-paste backend)
    (ansi-enable-focus-reporting backend)
    (ansi-enable-kitty-keyboard backend)
    (ansi-enable-synchronized-updates backend)
    (is-equal :any-motion (ansi-backend-mouse-mode backend))
    (is (ansi-backend-mouse-sgr-p backend))
    (is (ansi-backend-bracketed-paste-enabled-p backend))
    (is (ansi-backend-focus-reporting-enabled-p backend))
    (is-equal 1 (ansi-backend-kitty-keyboard-flags backend))
    (is (ansi-backend-synchronized-updates-enabled-p backend))
    (let ((surface (make-surface 2 1)))
      (surface-draw-text surface 0 0 "x")
      (backend-present backend surface))
    (let ((output (get-output-stream-string stream)))
      (is (search (format nil "~C[?1003h" (code-char 27)) output))
      (is (search (format nil "~C[?1006h" (code-char 27)) output))
      (is (search (format nil "~C[?2004h" (code-char 27)) output))
      (is (search (format nil "~C[?1004h" (code-char 27)) output))
      (is (search (format nil "~C[>1u" (code-char 27)) output))
      (is (search (format nil "~C[?2026h" (code-char 27)) output))
      (is (search (format nil "~C[?2026l" (code-char 27)) output)))
    (backend-close backend)
    (let ((output (get-output-stream-string stream)))
      (is (search (format nil "~C[?1003l" (code-char 27)) output))
      (is (search (format nil "~C[?1006l" (code-char 27)) output))
      (is (search (format nil "~C[?2004l" (code-char 27)) output))
      (is (search (format nil "~C[?1004l" (code-char 27)) output))
      (is (search (format nil "~C[<u" (code-char 27)) output))
      (is (search (format nil "~C[0m" (code-char 27)) output)))
    (is-equal :closed (backend-state backend))
    (is (null (ansi-backend-mouse-mode backend)))
    (is (null (ansi-backend-mouse-sgr-p backend)))
    (is (null (ansi-backend-bracketed-paste-enabled-p backend)))
    (is (null (ansi-backend-focus-reporting-enabled-p backend)))
    (is (null (ansi-backend-kitty-keyboard-flags backend)))
    (is (null (ansi-backend-synchronized-updates-enabled-p backend)))))
