(in-package #:cl-tui-kit/tests)

(deftest geometry-and-invalid-dimensions (:core)
  (is-equal 0 (size-width (make-size -3 4)))
  (is-equal 4 (size-height (make-size -3 4)))
  (is (signals-error (make-size 1.5 2)))
  (let* ((outer (test-rectangle 0 0 4 3))
         (inner (test-rectangle 2 1 4 3))
         (intersection (rectangle-intersection outer inner)))
    (is-equal 2 (rectangle-width intersection))
    (is-equal 2 (rectangle-height intersection))
    (is (rectangle-contains-point-p outer 1 1))
    (is (not (rectangle-contains-point-p outer 4 1)))
    (is (rectangle-contains-rectangle-p outer
                                         (test-rectangle 1 1 2 1)))))

(deftest padding-constraints-and-viewport (:geometry)
  (let* ((padding (make-padding :top 1 :right 2 :bottom 3 :left 4))
         (inset (rectangle-inset (test-rectangle 0 0 10 8) padding))
         (constraints (make-constraints :min-width 3 :preferred-width 8
                                        :max-width 6 :flex-width 1))
         (viewport (make-viewport :bounds (test-rectangle 0 0 4 2)
                                  :content-width 10
                                  :content-height 8)))
    (is-equal 4 (rectangle-x inset))
    (is-equal 4 (rectangle-width inset))
    (is-equal 6 (resolve-axis 20 constraints :width))
    (viewport-scroll-to viewport 99 99)
    (is-equal 6 (viewport-offset-x viewport))
    (is-equal 6 (viewport-offset-y viewport))
    (is (rectangle-contains-point-p
         (viewport-visible-rectangle viewport) 6 6)))
  (is (signals-error (make-constraints :min-width 10 :max-width 3)))
  (is (signals-error (make-constraints :min-height 10 :max-height 3))))

(deftest geometry-unions-copies-and-scroll-bounds (:geometry)
  (let* ((point (make-point -2 3))
         (point-copy (copy-point point))
         (rectangle (test-rectangle -2 1 4 3))
         (rectangle-copy (copy-rectangle rectangle))
         (empty (test-rectangle 0 0 0 3)))
    (is-equal -2 (point-x point-copy))
    (is-equal 3 (point-y point-copy))
    (is (rectangle-contains-point-p rectangle point))
    (is (rectangle-contains-point-p rectangle -1 3))
    (is (not (rectangle-contains-point-p rectangle 2 3)))
    (is-equal rectangle rectangle-copy)
    (is (not (rectangle-empty-p rectangle)))
    (is (rectangle-empty-p empty))
    (is (rectangle-contains-rectangle-p rectangle
                                         (make-rectangle 0 0 0 0)))
    (is (not (rectangle-contains-rectangle-p rectangle
                                              (test-rectangle 0 0 5 1)))))
  (let ((left (test-rectangle 1 2 3 4))
        (right (test-rectangle 4 0 2 3)))
    (is-equal (test-rectangle 1 0 5 6)
              (rectangle-union left right)))
  (let ((empty (make-rectangle))
        (rectangle (test-rectangle 2 3 4 5)))
    (is-equal rectangle (rectangle-union empty rectangle))
    (is-equal rectangle (rectangle-union rectangle empty))
    (is (rectangle-empty-p
         (rectangle-intersection rectangle (test-rectangle 9 9 2 2))))
    (is-equal (test-rectangle -1 1 4 5)
              (rectangle-offset rectangle -3 -2)))
  (let* ((padding (make-padding :all 2))
         (padding-copy (copy-padding padding))
         (margin (make-margin :all 3))
         (margin-copy (copy-margin margin))
         (region (make-clipping-region (test-rectangle 1 2 3 4))))
    (is-equal 2 (padding-left padding-copy))
    (is-equal 3 (margin-bottom margin-copy))
    (is-equal (test-rectangle 1 2 3 4)
              (clipping-region-rectangle region))
    (is (not (eq (clipping-region-rectangle region)
                 (clipping-region-rectangle
                  (make-clipping-region (clipping-region-rectangle region)))))))
  (let* ((constraints (make-constraints :min-width 2
                                        :preferred-width 6
                                        :max-width 8
                                        :min-height 3
                                        :preferred-height 5
                                        :max-height 4
                                        :flex-width 1
                                        :flex-height 2))
         (copy (copy-constraints constraints)))
    (is (not (eq constraints copy)))
    (is-equal 2 (constraints-min-width copy))
    (is-equal 6 (constraints-preferred-width copy))
    (is-equal 8 (constraints-max-width copy))
    (is-equal 3 (constraints-min-height copy))
    (is-equal 5 (constraints-preferred-height copy))
    (is-equal 4 (constraints-max-height copy))
    (is-equal 1 (constraints-flex-width copy))
    (is-equal 2 (constraints-flex-height copy))
    (is-equal 4 (resolve-axis 10 constraints :height))
    (is-equal 2 (resolve-axis 2 constraints :height))
    (is-equal 0 (resolve-axis -1 constraints :height)))
  (is (signals-error (make-point 1.5 0)))
  (is (signals-error (make-rectangle 0 0 1.5 1)))
  (is (signals-error (make-constraints :flex-width -1)))
  (is (signals-error (make-constraints :flex-height :invalid)))
  (let ((viewport (make-viewport :bounds (test-rectangle 0 0 4 2)
                                 :content-width 3
                                 :content-height 1
                                 :offset-x -2
                                 :offset-y -3)))
    (is-equal 0 (viewport-scroll-x-max viewport))
    (is-equal 0 (viewport-scroll-y-max viewport))
    (is-equal 0 (viewport-offset-x viewport))
    (is-equal 0 (viewport-offset-y viewport))
    (viewport-scroll-by viewport 10 10)
    (is-equal (test-rectangle 0 0 4 2)
              (viewport-visible-rectangle viewport))))

(deftest style-and-theme (:style)
  (let* ((base (make-style :bold t :foreground (named-color :blue)))
         (overlay (make-style :underline t :foreground (rgb-color 1 2 3)))
         (merged (merge-styles base overlay))
         (theme (make-theme)))
    (is (style-bold merged))
    (is (style-underline merged))
    (is (color= (style-foreground merged) (rgb-color 1 2 3)))
    (let ((background-merged
            (merge-styles base (make-style :background (rgb-color 4 5 6)))))
      (is (color= (style-background background-merged)
                  (rgb-color 4 5 6))))
    (theme-set-style theme :accent merged)
    (is (style= merged (theme-style theme :accent)))
    (is (color= (default-color) (make-color :default)))
    (is (color= (indexed-color 42) (make-color :indexed 42)))
    (is (color= (rgb-color 1 2 3) (make-color :rgb (list 1 2 3))))
    (is (not (color= (named-color :red) (named-color :blue))))
    (is (not (color= (rgb-color 1 2 3) :not-a-color)))
    (is (signals-error (make-color "not-a-symbol")))
    (is (signals-error (indexed-color -1)))
    (is (signals-error (indexed-color 256)))
    (is (signals-error (rgb-color 1 256 3)))
    (let ((copy (copy-style merged)))
      (is (style= merged copy))
      (is (not (style= merged (make-style))))
      (is (not (style= merged nil))))
    (let* ((seed (make-theme (list (cons :base base))))
           (copy (copy-theme seed)))
      (is (style= base (theme-style copy :base)))
      (is-equal :fallback (theme-style copy :missing :fallback))
      (is (eq copy
              (theme-set-style copy :base (make-style :italic t))))
      (is (style-italic (theme-style copy :base))))
    (is (style-bold (theme-style (default-theme) :accent)))
    (is (signals-error (theme-set-style theme "accent" base)))
    (is (signals-error (theme-set-style theme :accent nil)))))

(deftest unicode-cell-width-and-truncation (:text)
  (let* ((wide (code-char #x65E5))
         (combining (code-char #x0301))
         (emoji (code-char #x1F600))
         (mixed (format nil "A~C e~C~C" wide combining emoji)))
    (is-equal 2 (cell-width wide))
    (is-equal 0 (cell-width combining))
    (is-equal 2 (cell-width emoji))
    (is-equal 7 (string-cell-width mixed))
    (is-equal 4 (string-cell-width (format nil "a~C" #\Tab)
                                   :tab-width 4))
    (is-equal "a" (clip-text (format nil "a~C" wide) 2))
    (is-equal "日" (clip-text (format nil "~C" wide) 2))
    (is-equal "abc…" (truncate-text "abcdef" 4))
    (is-equal 2 (string-cell-width (format nil "ab~Ccd" #\Newline)))))

(deftest text-and-surface-edge-contracts (:text-surface-edges)
  (let* ((zwj (code-char #x200D))
         (woman (code-char #x1F469))
         (laptop (code-char #x1F4BB))
         (variation-selector (code-char #xFE0F))
         (emoji-modifier (code-char #x1F3FB))
         (cluster (format nil "~C~C~C" woman zwj laptop))
         (units (text-units cluster))
         (variation-unit (format nil "~C~C" (code-char #x2764)
                                 variation-selector))
         (modifier-unit (format nil "~C~C" (code-char #x1F44D)
                                emoji-modifier)))
    (is-equal 1 (length units))
    (is-equal 2 (text-unit-width (first units)))
    (is-equal 0 (cell-width variation-selector))
    (is-equal 0 (cell-width emoji-modifier))
    (is-equal 1 (length (text-units variation-unit)))
    (is-equal 1 (text-unit-width (first (text-units variation-unit))))
    (is-equal 1 (length (text-units modifier-unit)))
    (is-equal 2 (text-unit-width (first (text-units modifier-unit))))
    (is-equal 0 (cell-width (code-char 1))))
  (is-equal "ab"
            (clip-text (format nil "ab~Ccd" #\Newline) 10))
  (is (signals-error (clip-text "x" -1)))
  (let ((surface (make-surface 4 1)))
    (is-equal " " (cell-content (blank-cell)))
    (surface-draw-text surface 0 0 (format nil "x~Cz" #\Tab)
                        :max-width 1)
    (is-equal "x   " (surface-string surface))
    (is (signals-error (surface-draw-styled-text
                        surface 0 0 nil :tab-width 0)))
    (is (signals-error (surface-draw-styled-text
                        surface 0 0 (list "invalid-span"))))
    (is (signals-error (make-cell "x" :style)))
    (is (signals-error (make-cell "x" :span -1)))
    (is (signals-error (make-cell "x" :continuation-p t :span 1)))))

(deftest surface-clipping-dirty-and-diff (:surface)
  (let* ((surface (make-surface 8 3))
         (previous (copy-surface surface)))
    (surface-draw-text surface 0 0 "A日本")
    (is-equal (format nil "A日本   ~C        ~C        " #\Newline #\Newline)
              (surface-string surface))
    (is (surface-dirty-regions surface))
    (surface-set-clip surface (make-clipping-region (test-rectangle 0 1 3 1)))
    (surface-draw-text surface 0 0 "hidden")
    (is-equal (format nil "A日本   ~C        ~C        " #\Newline #\Newline)
              (surface-string surface))
    (surface-set-clip surface nil)
    (surface-fill-rectangle surface (test-rectangle 0 2 2 1)
                             "x")
    (is (consp (surface-diff surface previous)))
    (is (surface-cell surface 0 2))))

(deftest styled-spans-and-text-layout (:surface-styled)
  (let* ((surface (make-surface 8 2))
         (bold (make-style :bold t))
         (underlined (make-style :underline t))
         (italic (make-style :italic t))
         (spans (list (make-text-span "A" :style bold)
                      (make-text-span "日" :style underlined)
                      (make-text-span (format nil "~Cz" #\Newline)
                                      :style italic))))
    (surface-draw-styled-text surface 0 0 spans :max-width 5 :tab-width 4)
    (is (style-bold (cell-style (surface-cell surface 0 0))))
    (is (style-underline (cell-style (surface-cell surface 1 0))))
    (is (cell-continuation-p (surface-cell surface 2 0)))
    (is (style-italic (cell-style (surface-cell surface 0 1))))
    (let ((source (make-style :bold t))
          (span nil))
      (setf span (make-text-span "x" :style source)
            (style-bold source) nil)
      (is (style-bold (text-span-style span))))))

(deftest surface-border-and-blit (:surface)
  (let* ((source (make-surface 4 2))
         (target (make-surface 8 3)))
    (surface-draw-border source (test-rectangle 0 0 4 2))
    (surface-blit target source :destination-point (make-point 2 1))
    (is-equal "┌" (cell-content (surface-cell target 2 1)))
    (is-equal "┐" (cell-content (surface-cell target 5 1)))))

(deftest wide-cell-unit-invariants-and-blit (:surface-wide-cells)
  (let* ((surface (make-surface 6 1))
         (source (make-surface 4 1))
         (destination (make-surface 4 1)))
        (surface-draw-text surface 0 0 "日")
        (is (cell-continuation-p (surface-cell surface 1 0)))
        (surface-draw-text surface 3 0 (string (code-char #x0301)))
        (surface-put-cell surface 1 0 (make-cell "x"))
        (is (not (cell-continuation-p (surface-cell surface 1 0))))
    (is-equal " x    " (surface-string surface))
    (surface-draw-text source 0 0 "日x")
    (surface-blit destination source
                  :source-rectangle (make-rectangle 0 0 1 1))
    (is-equal "    " (surface-string destination))
        (surface-blit destination source)
        (is (cell-continuation-p (surface-cell destination 1 0)))
        (surface-put-cell destination 1 0 (make-cell "z"))
        (is-equal " zx " (surface-string destination))
        (surface-draw-text destination 0 0 "日")
        (surface-put-cell destination 1 0
                          (make-cell "" :span 0 :continuation-p t))
        (is-equal "  x " (surface-string destination))
        (surface-draw-text surface 5 0 "日")
    (is (not (cell-continuation-p (surface-cell surface 5 0))))
    (is (signals-error (make-cell "日" :span 1)))
    (is (signals-error (make-cell "" :span 1)))
    (let ((malformed (make-cell "x")))
      (setf (cell-content malformed) "日"
            (cell-span malformed) 1)
      (is (signals-error (surface-put-cell surface 0 0 malformed))))))
