(in-package #:cl-tui-kit/tests)

(deftest list-and-tree-model-events (:widgets)
  (let ((default-model
          (make-list-model
           :count 1
           :item-at (lambda (index)
                      (declare (ignore index))
                      "default"))))
    (is (signals-error
         (make-list-model :count :invalid
                          :item-at (lambda (index)
                                     (declare (ignore index))
                                     index))))
    (is (signals-error (make-list-model :count 0 :item-at nil)))
    (is-equal "default"
              (list-model-key-at default-model "default" 0))
    (is-equal "default"
              (list-model-label-at default-model "default" 0))
    (is-equal "default"
              (list-model-render-item default-model "default" 0))
    (let ((widget (make-list-widget default-model)))
      (is-equal 0 (rectangle-width (widget-rectangle widget)))
      (is-equal 0 (rectangle-height (widget-rectangle widget)))
      (is-equal 0 (list-widget-offset widget))
      (is-equal 1 (list-widget-row-height widget))
      (is-equal 7 (size-width (widget-preferred-size widget)))
      (is-equal 10 (size-height (widget-preferred-size widget))))
    (is (signals-error (make-list-widget default-model :row-height 0))))
  (let* ((items (vector "a" "b" "c" "d"))
         (model (make-list-model
                 :count (lambda () (length items))
                 :item-at (lambda (index) (aref items index))
                 :key-at (lambda (item index)
                           (declare (ignore index))
                           item)
                 :label-at (lambda (item index)
                             (declare (ignore index))
                             (format nil "label-~A" item))
                 :render-item (lambda (item index)
                                (declare (ignore index))
                                (format nil "render-~A" item))))
         (widget (make-list-widget model :selected-key "a"
                                   :row-height 1
                                   :rectangle (test-rectangle 0 0 12 2)))
         (surface (make-surface 12 2)))
    (is-equal 4 (list-model-count model))
    (is-equal "label-a" (list-model-label-at model "a" 0))
    (is-equal "render-a" (list-model-render-item model "a" 0))
    (is-equal "a" (list-model-key-at model "a" 0))
    (is-equal 2 (length (list-widget-visible-items widget)))
    (widget-render widget surface)
    (is (search "render-a" (surface-string surface)))
    (let ((info (widget-accessibility-tree widget)))
      (is-equal :listbox (getf info :role))
      (is-equal 4 (getf (getf info :state) :count)))
    (is-equal :move
              (action-name (handle-widget-event widget (make-key-event :down))))
    (is-equal "b" (list-widget-selected-key widget))
    (let ((action (handle-widget-event widget (make-key-event :up))))
      (is-equal :move (action-name action))
      (is-equal '(:direction :up :amount 1) (action-payload action)))
    (is-equal "a" (list-widget-selected-key widget))
    (handle-widget-event widget (make-key-event :end))
    (is-equal "d" (list-widget-selected-key widget))
    (handle-widget-event widget (make-key-event :page-up))
    (is-equal "b" (list-widget-selected-key widget))
    (handle-widget-event widget (make-key-event :page-down))
    (is-equal "d" (list-widget-selected-key widget))
    (handle-widget-event widget (make-key-event :home))
    (is-equal :toggle
              (action-name (handle-widget-event widget (make-key-event :space))))
    (is-equal "a"
              (action-payload (handle-widget-event widget (make-key-event :enter))))
    (let ((action (handle-widget-event widget (make-mouse-event 0 1))))
      (is-equal :select (action-name action))
      (is-equal "b" (action-payload action)))
    (setf items #("a" "b"))
    (list-widget-refresh widget)
    (is-equal "b" (list-widget-selected-key widget))
    (setf items #("a" "c"))
    (list-widget-refresh widget)
    (is-equal "a" (list-widget-selected-key widget))
    (setf items #())
    (list-widget-refresh widget)
    (is (null (list-widget-selected-key widget)))
    (is (null (list-widget-visible-items widget))))
  (let* ((expanded (make-hash-table :test #'equal))
         (nested-model (make-list-model
                        :count 1
                        :item-at (lambda (index)
                                   (declare (ignore index))
                                   :nested)
                        :key-at (lambda (item index)
                                  (declare (ignore index))
                                  item)
                        :label-at (lambda (item index)
                                    (declare (ignore index))
                                    (format nil "label-~A" item))))
         (roots #(:root :second))
         (model (make-tree-model
                 :root-count (lambda () (length roots))
                 :root-at (lambda (index) (aref roots index))
                 :key-at (lambda (node) node)
                 :label-at (lambda (node) (format nil "label-~A" node))
                 :children (lambda (node)
                             (cond ((eq node :root) #(:child-a :child-b))
                                   ((eq node :second) nested-model)))
                 :expanded-p (lambda (node) (gethash node expanded))
                 :render-item (lambda (node) (format nil "row-~A" node))))
         (widget (make-tree-widget model :selected-key :root
                                   :rectangle (test-rectangle 0 0 16 2)))
         (surface (make-surface 16 2)))
    (setf (gethash :root expanded) t
          (gethash :second expanded) t)
    (is-equal 2 (tree-model-root-count model))
    (is-equal 2 (length (tree-model-children model :root)))
    (is-equal :nested (tree-model-key-at model :nested))
    (widget-render widget surface)
    (is (search "row-ROOT" (surface-string surface)))
    (is (search "row-CHILD-A" (surface-string surface)))
    (let ((info (widget-accessibility-tree widget)))
      (is-equal :tree (getf info :role))
      (is-equal :root (getf (getf info :state) :selected-key)))
    (is-equal :move
              (action-name (handle-widget-event widget (make-key-event :down))))
    (is-equal :child-a (tree-widget-selected-key widget))
    (is-equal :expand
              (action-name (handle-widget-event widget (make-key-event :right))))
    (is-equal :collapse
              (action-name (handle-widget-event widget (make-key-event :left))))
    (is-equal :toggle
              (action-name (handle-widget-event widget (make-key-event :space))))
    (is-equal :child-a
              (action-payload (handle-widget-event widget (make-key-event :enter))))
    (handle-widget-event widget (make-key-event :end))
    (is-equal :nested (tree-widget-selected-key widget))
    (let ((action (handle-widget-event widget (make-mouse-event 0 0))))
      (is-equal :select (action-name action))
      (is-equal :second (action-payload action)))
    (handle-widget-event widget (make-key-event :page-up))
    (is-equal :child-a (tree-widget-selected-key widget))
    (let ((action (handle-widget-event widget (make-mouse-event 0 0))))
      (is-equal :select (action-name action))
      (is-equal :child-a (action-payload action)))
    (setf roots #(:second :third))
    (tree-widget-refresh widget)
    (is-equal :nested (tree-widget-selected-key widget))
    (setf roots #(:third))
    (tree-widget-refresh widget)
    (is-equal :third (tree-widget-selected-key widget))
    (setf roots #())
    (tree-widget-refresh widget)
    (is (null (tree-widget-selected-key widget)))))
