(in-package #:cl-tui-kit/core)

;;;; A deliberately small, centralized terminal-cell width policy.
;;;; It groups combining marks and ZWJ sequences well enough for normal TUI
;;;; labels, while documenting that it is not a full UAX #29 implementation.

(defparameter *ambiguous-width* :narrow
  "Width policy for East Asian Ambiguous characters: :NARROW or :WIDE.")

(defmacro with-ambiguous-width ((width) &body body)
  `(let ((*ambiguous-width* ,width))
     ,@body))

(defun %unicode-range-p (code low high)
  (<= low code high))

(defun %combining-code-p (code)
  (or (%unicode-range-p code #x0300 #x036f)
      (%unicode-range-p code #x0483 #x0489)
      (%unicode-range-p code #x0591 #x05bd)
      (%unicode-range-p code #x05bf #x05c7)
      (%unicode-range-p code #x0610 #x061a)
      (%unicode-range-p code #x064b #x065f)
      (%unicode-range-p code #x0670 #x0670)
      (%unicode-range-p code #x06d6 #x06ed)
      (%unicode-range-p code #x0711 #x0711)
      (%unicode-range-p code #x0730 #x074a)
      (%unicode-range-p code #x07a6 #x07b0)
      (%unicode-range-p code #x07eb #x07f3)
      (%unicode-range-p code #x0816 #x0819)
      (%unicode-range-p code #x081b #x0823)
      (%unicode-range-p code #x0825 #x0827)
      (%unicode-range-p code #x0829 #x082d)
      (%unicode-range-p code #x0859 #x085b)
      (%unicode-range-p code #x08d3 #x08e1)
      (%unicode-range-p code #x0900 #x0903)
      (%unicode-range-p code #x093a #x093c)
      (%unicode-range-p code #x093e #x094f)
      (%unicode-range-p code #x0951 #x0957)
      (%unicode-range-p code #x0962 #x0963)
      (%unicode-range-p code #x0981 #x0983)
      (%unicode-range-p code #x09bc #x09bc)
      (%unicode-range-p code #x09be #x09cd)
      (%unicode-range-p code #x0a01 #x0a03)
      (%unicode-range-p code #x0a3c #x0a51)
      (%unicode-range-p code #x0a70 #x0a71)
      (%unicode-range-p code #x0abc #x0abc)
      (%unicode-range-p code #x0abe #x0acf)
      (%unicode-range-p code #x0b01 #x0b03)
      (%unicode-range-p code #x0b3c #x0b57)
      (%unicode-range-p code #x0bbe #x0bcd)
      (%unicode-range-p code #x0c00 #x0c56)
      (%unicode-range-p code #x0cbf #x0cdc)
      (%unicode-range-p code #x0d3b #x0d4d)
      (%unicode-range-p code #x0e31 #x0e4e)
      (%unicode-range-p code #x0eb1 #x0ecd)
      (%unicode-range-p code #x0f18 #x0f19)
      (%unicode-range-p code #x0f35 #x0f39)
      (%unicode-range-p code #x0f71 #x0f87)
      (%unicode-range-p code #x0f8d #x0fbc)
      (%unicode-range-p code #x102d #x103e)
      (%unicode-range-p code #x1056 #x1059)
      (%unicode-range-p code #x105e #x1060)
      (%unicode-range-p code #x1062 #x1064)
      (%unicode-range-p code #x1067 #x106d)
      (%unicode-range-p code #x1071 #x1074)
      (%unicode-range-p code #x1082 #x108d)
      (%unicode-range-p code #x135d #x135f)
      (%unicode-range-p code #x1712 #x1714)
      (%unicode-range-p code #x1732 #x1734)
      (%unicode-range-p code #x1752 #x1753)
      (%unicode-range-p code #x1772 #x1773)
      (%unicode-range-p code #x17b4 #x17d3)
      (%unicode-range-p code #x180b #x180d)
      (%unicode-range-p code #x18a9 #x18a9)
      (%unicode-range-p code #x1920 #x193b)
      (%unicode-range-p code #x1a17 #x1a1b)
      (%unicode-range-p code #x1ab0 #x1aff)
      (%unicode-range-p code #x1dc0 #x1dff)
      (%unicode-range-p code #x20d0 #x20ff)
      (%unicode-range-p code #xfe00 #xfe0f)
      (%unicode-range-p code #xfe20 #xfe2f)
      (%unicode-range-p code #xe0100 #xe01ef)))

(defun %emoji-modifier-p (code)
  (%unicode-range-p code #x1f3fb #x1f3ff))

(defun %wide-code-p (code)
  (or (%unicode-range-p code #x1100 #x115f)
      (%unicode-range-p code #x231a #x231b)
      (%unicode-range-p code #x2329 #x232a)
      (%unicode-range-p code #x23e9 #x23ec)
      (%unicode-range-p code #x23f0 #x23f0)
      (%unicode-range-p code #x23f3 #x23f3)
      (%unicode-range-p code #x25fd #x25fe)
      (%unicode-range-p code #x2614 #x2615)
      (%unicode-range-p code #x2648 #x2653)
      (%unicode-range-p code #x267f #x267f)
      (%unicode-range-p code #x2693 #x2693)
      (%unicode-range-p code #x26a1 #x26a1)
      (%unicode-range-p code #x26aa #x26ab)
      (%unicode-range-p code #x26bd #x26be)
      (%unicode-range-p code #x26c4 #x26c5)
      (%unicode-range-p code #x26ce #x26ce)
      (%unicode-range-p code #x26d4 #x26d4)
      (%unicode-range-p code #x26ea #x26ea)
      (%unicode-range-p code #x26f2 #x26f3)
      (%unicode-range-p code #x26f5 #x26f5)
      (%unicode-range-p code #x26fa #x26fa)
      (%unicode-range-p code #x26fd #x26fd)
      (%unicode-range-p code #x2705 #x2705)
      (%unicode-range-p code #x270a #x270b)
      (%unicode-range-p code #x2728 #x2728)
      (%unicode-range-p code #x274c #x274c)
      (%unicode-range-p code #x274e #x274e)
      (%unicode-range-p code #x2753 #x2755)
      (%unicode-range-p code #x2757 #x2757)
      (%unicode-range-p code #x2795 #x2797)
      (%unicode-range-p code #x27b0 #x27b0)
      (%unicode-range-p code #x27bf #x27bf)
      (%unicode-range-p code #x2b1b #x2b1c)
      (%unicode-range-p code #x2b50 #x2b50)
      (%unicode-range-p code #x2b55 #x2b55)
      (%unicode-range-p code #x2e80 #x303e)
      (%unicode-range-p code #x3040 #xa4cf)
      (%unicode-range-p code #xac00 #xd7a3)
      (%unicode-range-p code #xf900 #xfaff)
      (%unicode-range-p code #xfe10 #xfe19)
      (%unicode-range-p code #xfe30 #xfe6b)
      (%unicode-range-p code #xff01 #xff60)
      (%unicode-range-p code #xffe0 #xffe6)
      (%unicode-range-p code #x1f004 #x1f004)
      (%unicode-range-p code #x1f0cf #x1f0cf)
      (%unicode-range-p code #x1f18e #x1f18e)
      (%unicode-range-p code #x1f191 #x1f19a)
      (%unicode-range-p code #x1f1e6 #x1f1ff)
      (%unicode-range-p code #x1f201 #x1f202)
      (%unicode-range-p code #x1f21a #x1f21a)
      (%unicode-range-p code #x1f22f #x1f22f)
      (%unicode-range-p code #x1f232 #x1f23a)
      (%unicode-range-p code #x1f250 #x1f251)
      (%unicode-range-p code #x1f300 #x1faff)
      (%unicode-range-p code #x20000 #x3fffd)))

(defun %ambiguous-code-p (code)
  (or (%unicode-range-p code #x00a1 #x00a1)
      (%unicode-range-p code #x00a4 #x00a4)
      (%unicode-range-p code #x00a7 #x00a8)
      (%unicode-range-p code #x00aa #x00aa)
      (%unicode-range-p code #x00ad #x00ae)
      (%unicode-range-p code #x00b0 #x00b4)
      (%unicode-range-p code #x00b6 #x00ba)
      (%unicode-range-p code #x00bc #x00bf)
      (%unicode-range-p code #x0391 #x03a9)
      (%unicode-range-p code #x03b1 #x03c9)
      (%unicode-range-p code #x0401 #x0451)
      (%unicode-range-p code #x2010 #x2010)
      (%unicode-range-p code #x2013 #x2016)
      (%unicode-range-p code #x2018 #x2019)
      (%unicode-range-p code #x201c #x201d)
      (%unicode-range-p code #x2020 #x2022)
      (%unicode-range-p code #x2024 #x2027)
      (%unicode-range-p code #x2030 #x2030)
      (%unicode-range-p code #x2032 #x2033)
      (%unicode-range-p code #x203b #x203b)
      (%unicode-range-p code #x2103 #x2103)
      (%unicode-range-p code #x2121 #x2122)
      (%unicode-range-p code #x2190 #x21ff)
      (%unicode-range-p code #x2200 #x22ff)
      (%unicode-range-p code #x2300 #x23ff)
      (%unicode-range-p code #x2460 #x24ff)
      (%unicode-range-p code #x2500 #x257f)
      (%unicode-range-p code #x25a0 #x25ff)
      (%unicode-range-p code #x2600 #x26ff)
      (%unicode-range-p code #x2b00 #x2bff)))

(defun cell-width (character &optional (ambiguous-width *ambiguous-width*))
  "Return the terminal-cell width of one code point.

Combining characters, variation selectors, emoji modifiers, controls, and
zero-width joiners return zero.  Grapheme-like clusters should be passed to
TEXT-UNIT-WIDTH instead."
  (let ((code (char-code character)))
    (cond
      ((or (zerop code) (< code 32) (= code 127)) 0)
      ((or (%combining-code-p code)
           (= code #x200b) (= code #x200c) (= code #x200d)
           (%emoji-modifier-p code)) 0)
      ((%wide-code-p code) 2)
      ((and (eq ambiguous-width :wide) (%ambiguous-code-p code)) 2)
      (t 1))))

(defun text-units (text)
  "Split TEXT into approximate grapheme units.

The grouping covers combining marks, variation selectors, emoji modifiers,
and common ZWJ sequences.  It intentionally does not claim full Unicode
grapheme-cluster conformance; see docs/src/guide/text-layout.md."
  (check-type text string)
  (let ((units '())
        (current '())
        (join-next nil))
    (labels ((append-character (character)
               (push character current))
             (finish ()
               (when current
                 (push (coerce (nreverse current) 'string) units))
               (setf current nil)))
      (loop for character across text
            for code = (char-code character)
            do (cond
                 ((or (%combining-code-p code)
                      (%emoji-modifier-p code)
                      (%unicode-range-p code #xfe00 #xfe0f))
                  (append-character character))
                 ((= code #x200d)
                  (append-character character)
                  (setf join-next t))
                 (join-next
                  (append-character character)
                  (setf join-next nil))
                 (t
                  (finish)
                  (append-character character))))
      (finish)
      (nreverse units))))

(defun text-unit-width (unit &optional (ambiguous-width *ambiguous-width*))
  (let ((width 0))
    (loop for character across unit
          do (incf width (cell-width character ambiguous-width)))
    (min 2 width)))

(defun string-cell-width (text &key (tab-width 8)
                                     (ambiguous-width *ambiguous-width*))
  (unless (and (integerp tab-width) (plusp tab-width))
    (error "TAB-WIDTH must be a positive integer."))
  (let ((column 0)
        (maximum 0))
    (dolist (unit (text-units text) maximum)
      (cond
        ((string= unit (string #\Newline))
         (setf maximum (max maximum column) column 0))
        ((string= unit (string #\Tab))
         (let ((step (- tab-width (mod column tab-width))))
           (incf column step)))
        (t
         (incf column (text-unit-width unit ambiguous-width))))
      (setf maximum (max maximum column)))))

(defun clip-text (text max-width &key (tab-width 8)
                                      (ambiguous-width *ambiguous-width*))
  "Clip a single display line to MAX-WIDTH cells without splitting a unit."
  (unless (and (integerp max-width) (>= max-width 0))
    (error "MAX-WIDTH must be a non-negative integer."))
  (unless (and (integerp tab-width) (plusp tab-width))
    (error "TAB-WIDTH must be a positive integer."))
  (let ((column 0)
        (output (make-array 0 :element-type 'character :adjustable t
                              :fill-pointer 0)))
    (dolist (unit (text-units text) (coerce output 'string))
      (when (string= unit (string #\Newline))
        (return (coerce output 'string)))
      (let* ((unit-width (if (string= unit (string #\Tab))
                             (- tab-width (mod column tab-width))
                             (text-unit-width unit ambiguous-width)))
             (next (+ column unit-width)))
        (when (> next max-width)
          (return (coerce output 'string)))
        (if (string= unit (string #\Tab))
            (loop repeat unit-width
              do
              (vector-push-extend #\Space output))
            (loop for character across unit
                  do (vector-push-extend character output)))
        (setf column next)))))

(defun truncate-text (text max-width &key (ellipsis "…") (tab-width 8)
                                           (ambiguous-width *ambiguous-width*))
  "Return TEXT clipped to MAX-WIDTH cells, adding ELLIPSIS when needed."
  (unless (and (integerp max-width) (>= max-width 0))
    (error "MAX-WIDTH must be a non-negative integer."))
  (if (<= (string-cell-width text :tab-width tab-width
                             :ambiguous-width ambiguous-width)
          max-width)
      text
      (let ((ellipsis-width (string-cell-width ellipsis
                                                :tab-width tab-width
                                                :ambiguous-width ambiguous-width)))
        (cond
          ((zerop max-width) "")
          ((>= ellipsis-width max-width)
           (clip-text ellipsis max-width :tab-width tab-width
                                     :ambiguous-width ambiguous-width))
          (t
           (concatenate 'string
                        (clip-text text (- max-width ellipsis-width)
                                   :tab-width tab-width
                                   :ambiguous-width ambiguous-width)
                        ellipsis))))))
